# Generated by Django 3.2.4 on 2023-03-22 00:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=1024)),
                ('geojson', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Layer GeoJSON')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
