# Generated by Django 3.2.4 on 2023-03-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='created',
        ),
    ]
