# Generated by Django 3.2.4 on 2023-03-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0002_remove_layer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
