# Generated by Django 3.2.4 on 2023-03-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0003_layer_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
