# Generated by Django 3.2.4 on 2023-03-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0007_auto_20230329_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LayerAccessLog',
            new_name='LayerRequestLog',
        ),
    ]
