# Generated by Django 3.2.4 on 2023-03-29 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0009_alter_layerrequestlog_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerrequestlog',
            name='layer_name',
        ),
        migrations.AddField(
            model_name='layerrequestlog',
            name='app_id',
            field=models.SmallIntegerField(default=1, verbose_name='Application ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layerrequestlog',
            name='data',
            field=models.JSONField(default=[], verbose_name='Layer GeoJSON'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layerrequestlog',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
