# Generated by Django 3.2.4 on 2023-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0010_auto_20230329_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerrequestlog',
            name='response',
            field=models.JSONField(default={}, verbose_name='Response from SQS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layerrequestlog',
            name='data',
            field=models.JSONField(verbose_name='Request query from external system'),
        ),
    ]
