# Generated by Django 3.2.4 on 2023-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0011_auto_20230329_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerrequestlog',
            name='response',
            field=models.JSONField(default=[{}], verbose_name='Response from SQS'),
        ),
    ]
